name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  run-test:
    name: 'Run tests'
    runs-on: ubuntu-latest

    steps:
      - name: Git clone
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install JDK
        uses: ./.github/jdk/

      - name: Test
        run: mvn test

  package:
    name: 'Package'
    needs: run-test

    uses: ./.github/workflows/ci-package.yml

  run:
    name: 'Run'
    needs: package

    uses: ./.github/workflows/ci-run.yml