name: CI

on:
  pull_request:
    branches: [main]

# https://stackoverflow.com/questions/65242830/in-a-github-actions-workflow-is-there-a-way-to-have-multiple-jobs-reuse-the-sam

jobs:
  run-test:
    name: 'Run tests'
    runs-on: ubuntu-latest

    steps:
      - name: Git clone
        uses: actions/checkout@v2
        with:
          fetch-depth: 0


      - name: Install JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
          cache: 'maven'
          

      - name: Test
        run: mvn test


      - name: Package
        run: mvn package -D maven.test.skip


      - name: Run
        run: java -cp ./target/reusing_workflow-1.0-SNAPSHOT.jar org.example.Main
