name: PACKAGING

on:
  workflow_call:

jobs:
  call-workflow-in-local=repo:
    uses: './.github/workflows/callworkflow.yml'

    steps:
      - name: Git clone
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Package
        run: mvn package -D maven.test.skip
