name: RUNNING

on:
  pull_request:
    branches: [main]

jobs:
  call-workflow-in-local=repo:
    uses: './.github/workflows/packaging.yml'

    steps:
      - name: Git clone
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Run
        run: java -cp ./target/reusing_workflow-1.0-SNAPSHOT.jar org.example.Main
