name: TESTING

on:
  pull_request:
    branches: [ main ]

jobs:
  call-workflow-in-local-repo:
    uses: './.github/workflows/callworkflow.yml'

    steps:
      - name: Git clone
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Test
        run: mvn test